version: '2'
services:
  scraper:
    build: .
    environment:
    - "SPRING_PROFILES_ACTIVE=docker,livedb"
    - "FINANZBLICK_USER=${FINANZBLICK_USER}"
    - "FINANZBLICK_PW=${FINANZBLICK_PW}"
    - "DB_USER=${DB_USER}"
    - "DB_PW=${DB_PW}"
    volumes:
      - /exports:/opt/docker_share
      - /m2:/root/.m2

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
      - /exports:/home/seluser/Downloads
    user: root

volumes:
  exports: